/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopRouteImport } from './routes/top'
import { Route as SignRouteImport } from './routes/sign'
import { Route as RoleSelectorRouteImport } from './routes/role-selector'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FindSitterRouteImport } from './routes/find-sitter'
import { Route as DownloadApkRouteImport } from './routes/download-apk'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as ModeratorRouteRouteImport } from './routes/moderator/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeratorIndexRouteImport } from './routes/moderator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SitterUserIdRouteImport } from './routes/sitter.$userId'
import { Route as ModeratorUsersRouteImport } from './routes/moderator/users'
import { Route as ModeratorContentModerationRouteImport } from './routes/moderator/content-moderation'
import { Route as ModeratorComplaintsRouteImport } from './routes/moderator/complaints'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminFinancesRouteImport } from './routes/admin/finances'
import { Route as AdminContentModerationRouteImport } from './routes/admin/content-moderation'
import { Route as AdminComplaintsRouteImport } from './routes/admin/complaints'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as SitterStripeRefreshRouteImport } from './routes/sitter.stripe.refresh'
import { Route as SitterStripeCompleteRouteImport } from './routes/sitter.stripe.complete'
import { Route as BookingsBookingIdPaymentResultRouteImport } from './routes/bookings_.$bookingId.payment-result'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders/$orderId'

const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectorRoute = RoleSelectorRouteImport.update({
  id: '/role-selector',
  path: '/role-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FindSitterRoute = FindSitterRouteImport.update({
  id: '/find-sitter',
  path: '/find-sitter',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadApkRoute = DownloadApkRouteImport.update({
  id: '/download-apk',
  path: '/download-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRouteRoute = ModeratorRouteRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorIndexRoute = ModeratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SitterUserIdRoute = SitterUserIdRouteImport.update({
  id: '/sitter/$userId',
  path: '/sitter/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorUsersRoute = ModeratorUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const ModeratorContentModerationRoute =
  ModeratorContentModerationRouteImport.update({
    id: '/content-moderation',
    path: '/content-moderation',
    getParentRoute: () => ModeratorRouteRoute,
  } as any)
const ModeratorComplaintsRoute = ModeratorComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ModeratorRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinancesRoute = AdminFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentModerationRoute = AdminContentModerationRouteImport.update({
  id: '/content-moderation',
  path: '/content-moderation',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SitterStripeRefreshRoute = SitterStripeRefreshRouteImport.update({
  id: '/sitter/stripe/refresh',
  path: '/sitter/stripe/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const SitterStripeCompleteRoute = SitterStripeCompleteRouteImport.update({
  id: '/sitter/stripe/complete',
  path: '/sitter/stripe/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdPaymentResultRoute =
  BookingsBookingIdPaymentResultRouteImport.update({
    id: '/bookings_/$bookingId/payment-result',
    path: '/bookings/$bookingId/payment-result',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/blocked': typeof BlockedRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/download-apk': typeof DownloadApkRoute
  '/find-sitter': typeof FindSitterRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/role-selector': typeof RoleSelectorRoute
  '/sign': typeof SignRoute
  '/top': typeof TopRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/content-moderation': typeof AdminContentModerationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/complaints': typeof ModeratorComplaintsRoute
  '/moderator/content-moderation': typeof ModeratorContentModerationRoute
  '/moderator/users': typeof ModeratorUsersRoute
  '/sitter/$userId': typeof SitterUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/bookings/$bookingId/payment-result': typeof BookingsBookingIdPaymentResultRoute
  '/sitter/stripe/complete': typeof SitterStripeCompleteRoute
  '/sitter/stripe/refresh': typeof SitterStripeRefreshRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/blocked': typeof BlockedRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/download-apk': typeof DownloadApkRoute
  '/find-sitter': typeof FindSitterRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/role-selector': typeof RoleSelectorRoute
  '/sign': typeof SignRoute
  '/top': typeof TopRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/content-moderation': typeof AdminContentModerationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/complaints': typeof ModeratorComplaintsRoute
  '/moderator/content-moderation': typeof ModeratorContentModerationRoute
  '/moderator/users': typeof ModeratorUsersRoute
  '/sitter/$userId': typeof SitterUserIdRoute
  '/admin': typeof AdminIndexRoute
  '/moderator': typeof ModeratorIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/bookings/$bookingId/payment-result': typeof BookingsBookingIdPaymentResultRoute
  '/sitter/stripe/complete': typeof SitterStripeCompleteRoute
  '/sitter/stripe/refresh': typeof SitterStripeRefreshRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/moderator': typeof ModeratorRouteRouteWithChildren
  '/ai-assistant': typeof AiAssistantRoute
  '/blocked': typeof BlockedRoute
  '/bookings': typeof BookingsRoute
  '/calendar': typeof CalendarRoute
  '/download-apk': typeof DownloadApkRoute
  '/find-sitter': typeof FindSitterRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/role-selector': typeof RoleSelectorRoute
  '/sign': typeof SignRoute
  '/top': typeof TopRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/content-moderation': typeof AdminContentModerationRoute
  '/admin/finances': typeof AdminFinancesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/users': typeof AdminUsersRoute
  '/moderator/complaints': typeof ModeratorComplaintsRoute
  '/moderator/content-moderation': typeof ModeratorContentModerationRoute
  '/moderator/users': typeof ModeratorUsersRoute
  '/sitter/$userId': typeof SitterUserIdRoute
  '/admin/': typeof AdminIndexRoute
  '/moderator/': typeof ModeratorIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/bookings_/$bookingId/payment-result': typeof BookingsBookingIdPaymentResultRoute
  '/sitter/stripe/complete': typeof SitterStripeCompleteRoute
  '/sitter/stripe/refresh': typeof SitterStripeRefreshRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/moderator'
    | '/ai-assistant'
    | '/blocked'
    | '/bookings'
    | '/calendar'
    | '/download-apk'
    | '/find-sitter'
    | '/home'
    | '/map'
    | '/profile'
    | '/role-selector'
    | '/sign'
    | '/top'
    | '/admin/complaints'
    | '/admin/content-moderation'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/users'
    | '/moderator/complaints'
    | '/moderator/content-moderation'
    | '/moderator/users'
    | '/sitter/$userId'
    | '/admin/'
    | '/moderator/'
    | '/admin/orders/$orderId'
    | '/bookings/$bookingId/payment-result'
    | '/sitter/stripe/complete'
    | '/sitter/stripe/refresh'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/blocked'
    | '/bookings'
    | '/calendar'
    | '/download-apk'
    | '/find-sitter'
    | '/home'
    | '/map'
    | '/profile'
    | '/role-selector'
    | '/sign'
    | '/top'
    | '/admin/complaints'
    | '/admin/content-moderation'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/users'
    | '/moderator/complaints'
    | '/moderator/content-moderation'
    | '/moderator/users'
    | '/sitter/$userId'
    | '/admin'
    | '/moderator'
    | '/admin/orders/$orderId'
    | '/bookings/$bookingId/payment-result'
    | '/sitter/stripe/complete'
    | '/sitter/stripe/refresh'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/moderator'
    | '/ai-assistant'
    | '/blocked'
    | '/bookings'
    | '/calendar'
    | '/download-apk'
    | '/find-sitter'
    | '/home'
    | '/map'
    | '/profile'
    | '/role-selector'
    | '/sign'
    | '/top'
    | '/admin/complaints'
    | '/admin/content-moderation'
    | '/admin/finances'
    | '/admin/logs'
    | '/admin/users'
    | '/moderator/complaints'
    | '/moderator/content-moderation'
    | '/moderator/users'
    | '/sitter/$userId'
    | '/admin/'
    | '/moderator/'
    | '/admin/orders/$orderId'
    | '/bookings_/$bookingId/payment-result'
    | '/sitter/stripe/complete'
    | '/sitter/stripe/refresh'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ModeratorRouteRoute: typeof ModeratorRouteRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRoute
  BlockedRoute: typeof BlockedRoute
  BookingsRoute: typeof BookingsRoute
  CalendarRoute: typeof CalendarRoute
  DownloadApkRoute: typeof DownloadApkRoute
  FindSitterRoute: typeof FindSitterRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  RoleSelectorRoute: typeof RoleSelectorRoute
  SignRoute: typeof SignRoute
  TopRoute: typeof TopRoute
  SitterUserIdRoute: typeof SitterUserIdRoute
  BookingsBookingIdPaymentResultRoute: typeof BookingsBookingIdPaymentResultRoute
  SitterStripeCompleteRoute: typeof SitterStripeCompleteRoute
  SitterStripeRefreshRoute: typeof SitterStripeRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-selector': {
      id: '/role-selector'
      path: '/role-selector'
      fullPath: '/role-selector'
      preLoaderRoute: typeof RoleSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-sitter': {
      id: '/find-sitter'
      path: '/find-sitter'
      fullPath: '/find-sitter'
      preLoaderRoute: typeof FindSitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-apk': {
      id: '/download-apk'
      path: '/download-apk'
      fullPath: '/download-apk'
      preLoaderRoute: typeof DownloadApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator': {
      id: '/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof ModeratorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/': {
      id: '/moderator/'
      path: '/'
      fullPath: '/moderator/'
      preLoaderRoute: typeof ModeratorIndexRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sitter/$userId': {
      id: '/sitter/$userId'
      path: '/sitter/$userId'
      fullPath: '/sitter/$userId'
      preLoaderRoute: typeof SitterUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderator/users': {
      id: '/moderator/users'
      path: '/users'
      fullPath: '/moderator/users'
      preLoaderRoute: typeof ModeratorUsersRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/moderator/content-moderation': {
      id: '/moderator/content-moderation'
      path: '/content-moderation'
      fullPath: '/moderator/content-moderation'
      preLoaderRoute: typeof ModeratorContentModerationRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/moderator/complaints': {
      id: '/moderator/complaints'
      path: '/complaints'
      fullPath: '/moderator/complaints'
      preLoaderRoute: typeof ModeratorComplaintsRouteImport
      parentRoute: typeof ModeratorRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/finances': {
      id: '/admin/finances'
      path: '/finances'
      fullPath: '/admin/finances'
      preLoaderRoute: typeof AdminFinancesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content-moderation': {
      id: '/admin/content-moderation'
      path: '/content-moderation'
      fullPath: '/admin/content-moderation'
      preLoaderRoute: typeof AdminContentModerationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sitter/stripe/refresh': {
      id: '/sitter/stripe/refresh'
      path: '/sitter/stripe/refresh'
      fullPath: '/sitter/stripe/refresh'
      preLoaderRoute: typeof SitterStripeRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitter/stripe/complete': {
      id: '/sitter/stripe/complete'
      path: '/sitter/stripe/complete'
      fullPath: '/sitter/stripe/complete'
      preLoaderRoute: typeof SitterStripeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings_/$bookingId/payment-result': {
      id: '/bookings_/$bookingId/payment-result'
      path: '/bookings/$bookingId/payment-result'
      fullPath: '/bookings/$bookingId/payment-result'
      preLoaderRoute: typeof BookingsBookingIdPaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminContentModerationRoute: typeof AdminContentModerationRoute
  AdminFinancesRoute: typeof AdminFinancesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminContentModerationRoute: AdminContentModerationRoute,
  AdminFinancesRoute: AdminFinancesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ModeratorRouteRouteChildren {
  ModeratorComplaintsRoute: typeof ModeratorComplaintsRoute
  ModeratorContentModerationRoute: typeof ModeratorContentModerationRoute
  ModeratorUsersRoute: typeof ModeratorUsersRoute
  ModeratorIndexRoute: typeof ModeratorIndexRoute
}

const ModeratorRouteRouteChildren: ModeratorRouteRouteChildren = {
  ModeratorComplaintsRoute: ModeratorComplaintsRoute,
  ModeratorContentModerationRoute: ModeratorContentModerationRoute,
  ModeratorUsersRoute: ModeratorUsersRoute,
  ModeratorIndexRoute: ModeratorIndexRoute,
}

const ModeratorRouteRouteWithChildren = ModeratorRouteRoute._addFileChildren(
  ModeratorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ModeratorRouteRoute: ModeratorRouteRouteWithChildren,
  AiAssistantRoute: AiAssistantRoute,
  BlockedRoute: BlockedRoute,
  BookingsRoute: BookingsRoute,
  CalendarRoute: CalendarRoute,
  DownloadApkRoute: DownloadApkRoute,
  FindSitterRoute: FindSitterRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  RoleSelectorRoute: RoleSelectorRoute,
  SignRoute: SignRoute,
  TopRoute: TopRoute,
  SitterUserIdRoute: SitterUserIdRoute,
  BookingsBookingIdPaymentResultRoute: BookingsBookingIdPaymentResultRoute,
  SitterStripeCompleteRoute: SitterStripeCompleteRoute,
  SitterStripeRefreshRoute: SitterStripeRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
